import React from "react";

import {
  Video,
  FlaskConical,
  UserCheck,
  BookOpen,
  GraduationCap,
  Users,
  MessageSquareText,
  FileQuestion,
  Brain,
  Map,
} from "lucide-react";

// Hero Section Component
const HeroSection: React.FC = () => {
  return (
    <section className="text-center py-12 bg-[#CBC3E3] text-black">
      <h2 className="text-5xl font-extrabold font-display">O Level Islamiat</h2>
      <p className="text-lg mt-2 font-display">
        Master Islamic Studies with our AI-powered O Level Islamiat assistant
      </p>
    </section>
  );
};

// Image Section Component
const ImageSection: React.FC = () => {
  return (
    <section className="flex justify-center py-12 bg-[#CBC3E3]">
      <img
        src="/public/islamiat3.jpg"
        alt="O Level Islamiat lesson content"
        className="w-[85%] shadow-lg rounded-lg"
      />
    </section>
  );
};

// Course Section Component
const CourseSection: React.FC = () => {
  return (
    <section className="py-16 px-10 flex items-center justify-between bg-white">
      <div className="w-1/2">
        <img
          src="/public/islamiat1.png"
          alt="Islamiat AI assistant preview"
          className="w-full rounded-lg shadow-lg"
        />
      </div>
      <div className="w-1/2 pl-10">
        <h2 className="text-3xl font-extrabold font-display">
          Your path to excellence in
          <br />O Level Islamiat
        </h2>
        <p className="mt-4 text-lg text-gray-700 font-display">
          Our O Level Islamiat AI assistant combines traditional teaching wisdom
          with cutting-edge AI technology. Explore the Quran, Hadith, and
          Islamic history through interactive lessons, personalized AI guidance,
          and comprehensive study materials designed to help you achieve top
          grades in your exams.
        </p>
        <div className="mt-6 flex gap-4">
          <button className="px-6 py-3 bg-black text-white font-bold rounded-md">
            Try for free
          </button>
          <button className="px-6 py-3 bg-black text-white font-bold rounded-md">
            Get Started
          </button>
        </div>
      </div>
    </section>
  );
};

// Video Lessons Section Component
const VideoLessonSection: React.FC = () => {
  return (
    <section className="py-16 px-10 flex items-center justify-between bg-white">
      <div className="w-1/2 pr-10">
        <h2 className="text-3xl font-extrabold font-display">
          AI teacher makes
          <br />
          Islamic studies accessible
        </h2>
        <p className="mt-4 text-lg text-gray-700 font-display">
          We've reimagined how O Level Islamiat is taught with our advanced AI
          teacher. Our assistant breaks down complex theological concepts into
          clear, digestible segments. You can ask questions, explore topics in
          depth, and receive personalized guidance throughout your learning
          journey, just like having a dedicated Islamiat teacher available 24/7.
        </p>
        <div className="mt-6 flex gap-4">
          <button className="px-6 py-3 bg-black text-white font-bold rounded-md">
            Try for free
          </button>
          <button className="px-6 py-3 bg-black text-white font-bold rounded-md">
            Get Started
          </button>
        </div>
      </div>
      <div className="w-1/2">
        <img
          src="/islamiat2.png"
          alt="AI-powered Islamiat assistant"
          className="w-full rounded-lg shadow-lg"
        />
      </div>
    </section>
  );
};

// Features Section Component
const FeaturesSection: React.FC = () => {
  const features = [
    {
      icon: <MessageSquareText className="h-12 w-12 text-blue-500" />,
      title: "Personal AI Teacher",
      description:
        "Get instant answers to your questions about Islamic concepts, history, and practices from your dedicated AI teacher.",
    },
    {
      icon: <FileQuestion className="h-12 w-12 text-green-500" />,
      title: "Past Paper AI Assistant",
      description:
        "Our AI analyzes past papers and provides personalized guidance for exam preparation.",
    },
    {
      icon: <Brain className="h-12 w-12 text-purple-500" />,
      title: "Interactive Quizzes",
      description:
        "Test your knowledge with adaptive quizzes generated by the AI that focus on your improvement areas.",
    },
    {
      icon: <Map className="h-12 w-12 text-yellow-500" />,
      title: "Topic Explorer",
      description:
        "Navigate through Islamic topics with our AI-guided interactive concept maps.",
    },
    {
      icon: <Video className="h-12 w-12 text-red-500" />,
      title: "Video Explanations",
      description:
        "Request AI-generated explanations on any topic in the O Level syllabus.",
    },
    {
      icon: <BookOpen className="h-12 w-12 text-pink-500" />,
      title: "AI-Generated Study Materials",
      description:
        "Access detailed study materials and revision guides tailored to your learning pace.",
    },
  ];

  return (
    <section className="py-16 px-10 bg-white text-center">
      <h2 className="text-3xl font-extrabold font-display">
        Your AI Islamiat teacher at your fingertips
      </h2>
      <p className="mt-4 text-lg text-gray-700">
        Our innovative approach combines traditional Islamic scholarship with
        modern AI technology
        <br />
        to create a teaching experience that's both authentic and effective.
      </p>
      <div className="grid grid-cols-3 gap-6 mt-10">
        {features.map((feature, index) => (
          <div
            key={index}
            className="p-6 border rounded-lg shadow-md text-left flex items-start gap-4"
          >
            {feature.icon}
            <div>
              <h3 className="text-xl font-bold">{feature.title}</h3>
              <p className="text-gray-600">{feature.description}</p>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
};

// Islamiat Page Component
const IslamiatPage: React.FC = () => {
  return (
    <div className="bg-[#CBC3E3] min-h-screen">
      <HeroSection />
      <ImageSection />
      <CourseSection />
      <VideoLessonSection />
      <FeaturesSection />
    </div>
  );
};

export default IslamiatPage;
